/** Display metadata for supported currency codes (keep in sync with server lib/currencyDefaults.js list). */

export const CURRENCY_FLAGS = {
  USD: '🇺🇸',
  EUR: '🇪🇺',
  GBP: '🇬🇧',
  INR: '🇮🇳',
  PHP: '🇵🇭',
  RUB: '🇷🇺',
  AED: '🇦🇪',
  SAR: '🇸🇦',
  PKR: '🇵🇰',
  BDT: '🇧🇩',
  NGN: '🇳🇬',
  BRL: '🇧🇷',
  CAD: '🇨🇦',
  AUD: '🇦🇺',
  JPY: '🇯🇵',
  CNY: '🇨🇳',
  TRY: '🇹🇷',
  MXN: '🇲🇽',
  IDR: '🇮🇩',
  THB: '🇹🇭',
  KRW: '🇰🇷',
  ZAR: '🇿🇦',
  CHF: '🇨🇭',
  NZD: '🇳🇿',
  SGD: '🇸🇬',
  HKD: '🇭🇰',
  PLN: '🇵🇱',
  SEK: '🇸🇪',
  NOK: '🇳🇴',
  DKK: '🇩🇰',
  MYR: '🇲🇾',
  VND: '🇻🇳',
  EGP: '🇪🇬',
  UAH: '🇺🇦',
  COP: '🇨🇴',
  ARS: '🇦🇷',
  QAR: '🇶🇦',
  KWD: '🇰🇼',
  ILS: '🇮🇱',
  CLP: '🇨🇱',
  PEN: '🇵🇪',
  CZK: '🇨🇿',
  HUF: '🇭🇺',
  LKR: '🇱🇰',
  NPR: '🇳🇵',
  KES: '🇰🇪',
  GHS: '🇬🇭',
  XOF: '🌍',
  MAD: '🇲🇦',
  TWD: '🇹🇼',
  BGN: '🇧🇬',
  RON: '🇷🇴',
};

export const CURRENCY_NAMES = {
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  INR: 'Indian Rupee',
  PHP: 'Philippine Peso',
  RUB: 'Russian Ruble',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  PKR: 'Pakistani Rupee',
  BDT: 'Bangladeshi Taka',
  NGN: 'Nigerian Naira',
  BRL: 'Brazilian Real',
  CAD: 'Canadian Dollar',
  AUD: 'Australian Dollar',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan',
  TRY: 'Turkish Lira',
  MXN: 'Mexican Peso',
  IDR: 'Indonesian Rupiah',
  THB: 'Thai Baht',
  KRW: 'South Korean Won',
  ZAR: 'South African Rand',
  CHF: 'Swiss Franc',
  NZD: 'New Zealand Dollar',
  SGD: 'Singapore Dollar',
  HKD: 'Hong Kong Dollar',
  PLN: 'Polish Zloty',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  MYR: 'Malaysian Ringgit',
  VND: 'Vietnamese Dong',
  EGP: 'Egyptian Pound',
  UAH: 'Ukrainian Hryvnia',
  COP: 'Colombian Peso',
  ARS: 'Argentine Peso',
  QAR: 'Qatari Riyal',
  KWD: 'Kuwaiti Dinar',
  ILS: 'Israeli Shekel',
  CLP: 'Chilean Peso',
  PEN: 'Peruvian Sol',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  LKR: 'Sri Lankan Rupee',
  NPR: 'Nepalese Rupee',
  KES: 'Kenyan Shilling',
  GHS: 'Ghanaian Cedi',
  XOF: 'West African CFA Franc',
  MAD: 'Moroccan Dirham',
  TWD: 'Taiwan Dollar',
  BGN: 'Bulgarian Lev',
  RON: 'Romanian Leu',
};

export const CURRENCY_SYMBOLS = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  INR: '₹',
  PHP: '₱',
  RUB: '₽',
  AED: 'د.إ',
  SAR: '﷼',
  PKR: '₨',
  BDT: '৳',
  NGN: '₦',
  BRL: 'R$',
  CAD: 'CA$',
  AUD: 'A$',
  JPY: '¥',
  CNY: '¥',
  TRY: '₺',
  MXN: 'MX$',
  IDR: 'Rp',
  THB: '฿',
  KRW: '₩',
  ZAR: 'R',
  CHF: 'CHF ',
  NZD: 'NZ$',
  SGD: 'S$',
  HKD: 'HK$',
  PLN: 'zł',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  MYR: 'RM',
  VND: '₫',
  EGP: 'E£',
  UAH: '₴',
  COP: 'COL$',
  ARS: 'AR$',
  QAR: 'QR',
  KWD: 'KD',
  ILS: '₪',
  CLP: 'CL$',
  PEN: 'S/',
  CZK: 'Kč',
  HUF: 'Ft',
  LKR: 'Rs',
  NPR: 'रू',
  KES: 'KSh',
  GHS: 'GH₵',
  XOF: 'CFA',
  MAD: 'DH',
  TWD: 'NT$',
  BGN: 'лв',
  RON: 'lei',
};

/** Prefer 0 decimal places for these when formatting whole-unit style amounts. */
export const ZERO_DECIMAL_CURRENCIES = new Set([
  'JPY',
  'KRW',
  'VND',
  'IDR',
  'CLP',
  'COP',
  'HUF',
  'XOF',
]);

/** Until /currencies loads, keep selector in sync with server default list shape. */
export const DEFAULT_FALLBACK_SUPPORTED = Object.keys(CURRENCY_FLAGS);
